# NameError:- This exception is raised when a variable or function
#             name is not found in the current scope.
def Print():
    try:
        n=11
        return m
    except:
        print("The variable is not defined in the function.")

print(Print())